---
- name: "Install Required Libraries & Dependencies"
  ansible.builtin.package:
    name:
      - curl
      - unzip
      - ca-certificates
      - gnupg
      - lsb-release
      - git
      - net-tools
      - jq
    state: present
    update_cache: yes

- name: "Install Prerequisite Directory"
  ansible.builtin.file:
    path: "/etc/apt/keyrings"
    owner: ubuntu
    group: ubuntu
    mode: "0755"

- name: "Download Docker Instance"
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    dest: "/etc/apt/keyrings/docker.asc"
    mode: "0644"

- name: "Set Up Docker Stable Repository"
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ 'noble' if ansible_distribution_release == 'resolute' else ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: "Update Repositores"
  ansible.builtin.package:
    update_cache: yes

- name: "Install Docker Infrastructure"
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: "Install AWS CLI"
  ansible.builtin.get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: "/tmp/awscliv2.zip"

- name: "Unzip AWS CLI Installer"
  ansible.builtin.unarchive:
    src: "/tmp/awscliv2.zip"
    dest: "/tmp"
    remote_src: yes

- name: "Run AWS CLI Installer"
  ansible.builtin.command:
    cmd: "/tmp/aws/install --update"
    creates: "/usr/local/bin/aws"
